/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "imsdk.h"
/* Header for class com_laixou_imsdk_IMSdk */

#ifndef _Included_com_laixou_imsdk_IMSdk
#define _Included_com_laixou_imsdk_IMSdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    setCallback
 * Signature: (Lcom/laixou/imsdk/IMSdk/ConnListener;)V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_setCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    connect
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    isConn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_laixou_imsdk_IMSdk_isConn
  (JNIEnv *, jobject);

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    send
 * Signature: (Lcom/laixou/imsdk/MessageBean;)V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_send
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
