/* DO NOT EDIT THIS FILE - it is machine generated */
#include "imsdk_jni.h"
#include <string.h>
#include "jni_tools.h"


/* Header for class com_laixou_imsdk_IMSdk */
//初始化的时候会调进来一次，在这个方法里持有jvm的引用


JavaVM *m_vm;

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    m_vm = vm;
    JNIEnv *env = NULL;
    jint result = -1;
    if (m_vm) {
        LOGD("m_vm init success");
    } else {
        LOGD("m_vm init failed");
    }
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_4) != JNI_OK) {
        return result;
    }
    return JNI_VERSION_1_4;
}

JNIEnv *getJNIEnv(int *needsDetach) {
    JNIEnv *env = NULL;
    jint result = -1;
    if ((*m_vm)->GetEnv(m_vm, (void **) &env, JNI_VERSION_1_4) != JNI_OK) {
        int status = (*m_vm)->AttachCurrentThread(m_vm, &env, 0);
        if (status < 0) {
            LOGD("failed to attach current thread");
            return NULL;
        }
        *needsDetach = 1;
    }
    return env;
}





//char *_sing="(Ljava/lang/String;)V";


static void onDisconn(char *msg) {
    LOGD("c连接断开:%s", msg);
}

static void getData(char *msg) {
    LOGD("c收到消息:%s", msg);
}

static void onConnErr(char *msg) {
    LOGD("c连接失败:%s", msg);
}

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    setCallback
 * Signature: (Lcom/laixou/imsdk/IMSdk/ConnListener;)V
 */


//    jclass cls = GetObjectClass(_env, _callback);
//    (*_env)->CallVoidMethod(_env, _callback, method,jmsg);

static jobject _callback;
char *_sing = "()V";

static void onConnect(char *msg) {
    int needsDetach;
    JNIEnv *_env = getJNIEnv(&needsDetach);
    jclass cls = (*_env)->GetObjectClass(_env, _callback);
    LOGD("C conn success:%s", msg);
    jmethodID method = GetMethodId(_env, cls, "onConn", _sing);
    (*_env)->CallVoidMethod(_env, _callback, method);
}

JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_setCallback(JNIEnv *env, jobject obj,
                                                               jobject callback) {
    // _callback = callback;
    _callback = (*env)->NewGlobalRef(env, callback);
    jclass callbackCls = (*env)->GetObjectClass(env, _callback);
    jmethodID onConnMethodId = (*env)->GetMethodID(env, callbackCls, "onConn", _sing);
    (*env)->CallVoidMethod(env, _callback, onConnMethodId);
    IMSDK_setCallback(onConnect, onDisconn, getData, onConnErr);
}

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    connect
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_connect(JNIEnv *env, jobject obj, jstring ipStr,
                                                           jint port) {

    char *ip = jstringToCharArr(env, ipStr);
    LOGD("conn:%s       %d ", ip, port);
    IMSDK_connect(ip, port);
    LOGD("isconn:%d", IMSDK_isconn());
}

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    isConn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_laixou_imsdk_IMSdk_isConn(JNIEnv *env, jobject obj) {
    return IMSDK_isconn();
}

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    send
 * Signature: (Lcom/laixou/imsdk/MessageBean;)V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_send(JNIEnv *env, jobject obj, jobject msg) {

    jclass cls = (*env)->GetObjectClass(env, msg);
    int cmd = getIntFromObj(env, msg, cls, "cmd");
    int sender = getIntFromObj(env, msg, cls, "sender");
    int receiver = getIntFromObj(env, msg, cls, "receiver");
    int msgid = getIntFromObj(env, msg, cls, "msgid");
    int msgscope = getIntFromObj(env, msg, cls, "msgscope");
//    int device = DEVICE_ANDROID;
    int status = getIntFromObj(env, msg, cls, "status");
    char *token = getStringFromObj(env, msg, cls, "token");
    char *version = getStringFromObj(env, msg, cls, "version");
    char *body = getStringFromObj(env, msg, cls, "body");
    char *chk = getStringFromObj(env, msg, cls, "chk");
    LOGD("cmd:%d\t"
                 "sender:%d\t"
                 "receiver:%d\t"
                 "msgid:%d\t"
                 "msgscope:%d\t"
                 "status:%d\t"
                 "token:%s\t"
                 "version:%s\t"
                 "body:%s\t"
                 "chk:%s\t",
         cmd, sender, receiver, msgid, msgscope, status, token, version, body, chk);

    struct IMSDK_JSON json;
    json.cmd = cmd;
    json.sender = sender;
    json.receiver = receiver;
    json.msgid = msgid;
    json.msgscope = msgscope;
    json.device = DEVICE_ANDROID;

    strcpy(json.token, token);
    strcpy(json.version, version);

    strcpy(json.body, body);
    json.status = status;
    strcpy(json.chk, chk);

    IMSDK_send(&json);
    LOGD("发送消息");
}

/*
 * Class:     com_laixou_imsdk_IMSdk
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_laixou_imsdk_IMSdk_close(JNIEnv *env, jobject obj) {
    IMSDK_close();
    (*env)->DeleteGlobalRef(env, _callback);
}
